# permissions for end users to edit kubesharkoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeshark
    app.kubernetes.io/managed-by: kustomize
  name: kubesharkoperator-editor-role
rules:
- apiGroups:
  - kubeshark.example.io
  resources:
  - kubesharkoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeshark.example.io
  resources:
  - kubesharkoperators/status
  verbs:
  - get
